### ISSUE TITLE
10-26 23:22:56.580: E/AndroidRuntime(1673): java.lang.NumberFormatException: Invalid int: "10:00"

### ISSUE THREAD

**Issue by paragsagar** [AndroidTresLeches/AADP_AndroidClient#54]
10-26 23:22:56.580: E/AndroidRuntime(1673): FATAL EXCEPTION: main
10-26 23:22:56.580: E/AndroidRuntime(1673): Process: com.tresleches.aadp, PID: 1673
10-26 23:22:56.580: E/AndroidRuntime(1673): java.lang.NumberFormatException: Invalid int: "10:00"
10-26 23:22:56.580: E/AndroidRuntime(1673):     at java.lang.Integer.invalidInt(Integer.java:137)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at java.lang.Integer.parse(Integer.java:374)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at java.lang.Integer.parseInt(Integer.java:365)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at java.lang.Integer.parseInt(Integer.java:331)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at com.tresleches.aadp.helper.DateHelper.getTime(DateHelper.java:35)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at com.tresleches.aadp.adapter.EventArrayAdapter.getView(EventArrayAdapter.java:94)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.AbsListView.obtainView(AbsListView.java:2263)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.ListView.makeAndAddView(ListView.java:1790)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.ListView.fillDown(ListView.java:691)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.ListView.fillFromTop(ListView.java:752)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.ListView.layoutChildren(ListView.java:1616)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.AbsListView.onLayout(AbsListView.java:2091)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.View.layout(View.java:14817)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewGroup.layout(ViewGroup.java:4631)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.View.layout(View.java:14817)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewGroup.layout(ViewGroup.java:4631)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.View.layout(View.java:14817)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewGroup.layout(ViewGroup.java:4631)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.View.layout(View.java:14817)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewGroup.layout(ViewGroup.java:4631)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:801)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.View.layout(View.java:14817)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewGroup.layout(ViewGroup.java:4631)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.View.layout(View.java:14817)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewGroup.layout(ViewGroup.java:4631)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.View.layout(View.java:14817)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewGroup.layout(ViewGroup.java:4631)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.View.layout(View.java:14817)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewGroup.layout(ViewGroup.java:4631)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.Choreographer.doCallbacks(Choreographer.java:574)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.Choreographer.doFrame(Choreographer.java:544)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.os.Handler.handleCallback(Handler.java:733)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.os.Handler.dispatchMessage(Handler.java:95)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.os.Looper.loop(Looper.java:136)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at android.app.ActivityThread.main(ActivityThread.java:5017)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at java.lang.reflect.Method.invokeNative(Native Method)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at java.lang.reflect.Method.invoke(Method.java:515)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
10-26 23:22:56.580: E/AndroidRuntime(1673):     at dalvik.system.NativeStart.main(Native Method)

**Comment by paragsagar** [comment]
Adding code something like will fix the bug
time = time.substring(0, time.indexOf(':')!=-1?time.indexOf(':'):time.length());//IN windows Date comes as 10:00

**Comment by paragsagar** [comment]
Added code as a part of pull request Splash Screen #55
