### ISSUE TITLE
Donate screen is crashing

### ISSUE THREAD

**Issue by fcduarte** [AndroidTresLeches/AADP_AndroidClient#64]
If you don't provide an amount and tap on "Donate" the app crashes. Here's the stacktrace:

```
10-27 22:45:49.854: E/AndroidRuntime(2548): FATAL EXCEPTION: main
10-27 22:45:49.854: E/AndroidRuntime(2548): java.lang.NumberFormatException: Invalid double: ""
10-27 22:45:49.854: E/AndroidRuntime(2548):     at java.lang.StringToReal.invalidReal(StringToReal.java:63)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at java.lang.StringToReal.parseDouble(StringToReal.java:248)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at java.lang.Double.parseDouble(Double.java:295)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at java.lang.Double.valueOf(Double.java:332)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at com.tresleches.aadp.fragment.DonateFragment.donate(DonateFragment.java:75)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at com.tresleches.aadp.fragment.DonateFragment.access$0(DonateFragment.java:71)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at com.tresleches.aadp.fragment.DonateFragment$1.onClick(DonateFragment.java:60)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at android.view.View.performClick(View.java:4240)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at android.view.View$PerformClick.run(View.java:17721)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at android.os.Handler.handleCallback(Handler.java:730)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at android.os.Handler.dispatchMessage(Handler.java:92)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at android.os.Looper.loop(Looper.java:137)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at android.app.ActivityThread.main(ActivityThread.java:5103)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at java.lang.reflect.Method.invokeNative(Native Method)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at java.lang.reflect.Method.invoke(Method.java:525)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
10-27 22:45:49.854: E/AndroidRuntime(2548):     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by paragsagar** [comment]
Resolved as a part of last merge
